#!/usr/bin/env node

/**
 * Module dependencies.
 */

 var app = require('./src/main');
 var http = require('http');
 var cmd = require('commander');
 var config = require('./config');

 cmd
 .version('0.1.42')
 .option('-p, --port <n>', 'Port to start the HTTP server', parseInt)
 .parse(process.argv);

var port = cmd.port || config.port;
app.set('port', port);

/**
 * Create HTTP server.
 */

 var server = http.createServer(app);

/**
 * Prepare the websocket to handle communication among
 * processes to their clients
 */ 

 var io = require('socket.io')(server);

/**
 * Listen on provided port, on all network interfaces.
 */

 server.listen(port);
 server.on('error', onError);
 server.on('listening', onListening);

/**
 * Event listener for HTTP server "error" event.
 */

 function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }
  var bind = typeof port === 'string'
  ? 'Pipe ' + port
  : 'Port ' + port;
  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
    console.error(bind + ' requires elevated privileges');
    process.exit(1);
    break;
    case 'EADDRINUSE':
    console.error(bind + ' is already in use');
    process.exit(1);
    break;
    default:
    throw error;
  }
}

/**
* Event listener for HTTP server "listening" event.
**/

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
  ? 'pipe ' + addr
  : 'port ' + addr.port;
  console.log('xway dashboard started on %s', bind);
}

process.on('uncaughtException', function (error) {
   io.emit('stderr', '' + error);
   console.trace(error);
});

exports.io = io;
exports.server = server;
